In [1]:
import pandas as pd

In [2]:
path_file = 'data/coffee_production.csv'
coffee_production_df = pd.read_csv(path_file)
coffee_production_df.head()

,coffee_type,1990_1991,1991_1992,1992_1993,1993_1994,1994_1995,1995_1996,1996_1997,1997_1998,1998_1999,...,2010_2011,2011_2012,2012_2013,2013_2014,2014_2015,2015_2016,2016_2017,2017_2018,2018_2019,2019_2020
0,Robusta,9660000,25980000,5160000,11700000,10560000,5040000,17460000,13260000,19260000,...,9600000,9600000,5040000,10320000,8580000,4860000,1380000,6900000,3240000,2460000
1,Arabica,863760000,1078800000,896820000,685320000,777840000,776280000,646740000,727320000,652080000,...,511380000,459180000,595620000,727440000,799980000,840540000,878040000,829440000,831960000,846000000
2,Robusta,900000,1080000,840000,960000,1080000,1080000,1080000,1140000,1020000,...,600000,660000,720000,720000,720000,720000,720000,720000,780000,720000
3,Robusta/Arabica,45420000,88140000,75300000,76500000,83940000,79020000,84240000,77580000,54960000,...,49680000,49860000,36480000,38280000,50700000,45720000,32280000,38280000,28920000,31020000
4,Robusta,2580000,3240000,2340000,2220000,4380000,2640000,2460000,3000000,1620000,...,1980000,4680000,3660000,1920000,2760000,2760000,2280000,2280000,2700000,2400000

In [3]:
# Group the data and summarize the production of each coffee type
group_data = coffee_production_df.groupby('coffee_type').sum()
group_data

,1990_1991,1991_1992,1992_1993,1993_1994,1994_1995,1995_1996,1996_1997,1997_1998,1998_1999,1999_2000,...,2010_2011,2011_2012,2012_2013,2013_2014,2014_2015,2015_2016,2016_2017,2017_2018,2018_2019,2019_2020
coffee_type,,,,,,,,,,,,,,,,,,,,,
Arabica,1807140000,2073960000,1895580000,1593720000,1715940000,1873440000,1665720000,1739400000,1686780000,1815000000,...,1846080000,1960020000,1992300000,2047680000,2075280000,2177340000,2429880000,2431260000,2445300000,2341020000
Arabica/Robusta,2399820000,2409960000,2787060000,2492700000,2503560000,1948140000,2615880000,2354940000,3043860000,3798120000,...,4000620000,3634680000,4025820000,3881640000,3785460000,3720480000,4042620000,3822840000,4603500000,4122780000
Robusta,266400000,354840000,228840000,198840000,269700000,228360000,390780000,326940000,257700000,485160000,...,162780000,248520000,212100000,253260000,198480000,171900000,153240000,185940000,214800000,200100000
Robusta/Arabica,1120440000,1237380000,999780000,1220280000,1109640000,1189320000,1526280000,1571940000,1543620000,1784760000,...,2395020000,2636400000,2840820000,3051960000,2958720000,3297840000,3113340000,3381540000,3084180000,3239280000

In [4]:
# Transpose the data
transpose_data = group_data.T
transpose_data

coffee_type     Arabica  Arabica/Robusta    Robusta  Robusta/Arabica
1990_1991    1807140000       2399820000  266400000       1120440000
1991_1992    2073960000       2409960000  354840000       1237380000
1992_1993    1895580000       2787060000  228840000        999780000
1993_1994    1593720000       2492700000  198840000       1220280000
1994_1995    1715940000       2503560000  269700000       1109640000
1995_1996    1873440000       1948140000  228360000       1189320000
1996_1997    1665720000       2615880000  390780000       1526280000
1997_1998    1739400000       2354940000  326940000       1571940000
1998_1999    1686780000       3043860000  257700000       1543620000
1999_2000    1815000000       3798120000  485160000       1784760000
2000_2001    1730520000       2683380000  380280000       2030460000
2001_2002    1848120000       2548980000  275040000       1801980000
2002_2003    1796580000       3610380000  270540000       1680000000
2003_2004    1780140000       2386860000  267540000       1895640000
2004_2005    1837200000       3019200000  219360000       1888980000
2005_2006    1834320000       2655240000  230280000       1950240000
2006_2007    2030700000       3607860000  280800000       2204640000
2007_2008    2037300000       3029220000  179100000       2064900000
2008_2009    1700040000       3838140000  273780000       2276100000
2009_2010    1760760000       3294660000  232380000       2384640000
2010_2011    1846080000       4000620000  162780000       2395020000
2011_2012    1960020000       3634680000  248520000       2636400000
2012_2013    1992300000       4025820000  212100000       2840820000
2013_2014    2047680000       3881640000  253260000       3051960000
2014_2015    2075280000       3785460000  198480000       2958720000
2015_2016    2177340000       3720480000  171900000       3297840000
2016_2017    2429880000       4042620000  153240000       3113340000
2017_2018    2431260000       3822840000  185940000       3381540000
2018_2019    2445300000       4603500000  214800000       3084180000
2019_2020    2341020000       4122780000  200100000       3239280000

In [5]:
# Correlation data
corr_matrix = transpose_data.corr(method='pearson').abs()
corr_matrix

coffee_type       Arabica  Arabica/Robusta   Robusta  Robusta/Arabica
coffee_type
Arabica          1.000000         0.623834  0.453044         0.743225
Arabica/Robusta  0.623834         1.000000  0.312663         0.826251
Robusta          0.453044         0.312663  1.000000         0.451428
Robusta/Arabica  0.743225         0.826251  0.451428         1.000000

In [13]:
# The strongest correlation.  Which two coffee types have the strongest correlation in production volumes over the years? 
strongest_corr = corr_matrix[corr_matrix != 1].unstack().sort_values(ascending=False).drop_duplicates()
strongest_corr.head(1)

coffee_type      coffee_type
Arabica/Robusta  Robusta/Arabica    0.826251
dtype: float64

In [14]:
# The weakest correlation.  Which two coffee types have the weakest correlation in production volumes over the years?
weakest_corr = corr_matrix[corr_matrix != 1].unstack().sort_values(ascending=True).drop_duplicates()
weakest_corr.head(1)

coffee_type      coffee_type
Arabica/Robusta  Robusta        0.312663
dtype: float64

- Examine the correlation matrix. Which two coffee types have the strongest correlation in production volumes over the years? What might this imply about their production dynamics?

- Two coffee types with the strongest correlation in production volumes over the years are Arabica/Robusta and Robusta/Arabica, with a correlation coefficient of 0.826251. This means that there is a strong relationship between the production volume of these two coffee types. If the production volume of one type increases or decreases, the production volume of the other type will also increase or decrease accordingly.
- There may be shared factors that influence the production of these two coffee types such as environmental conditions, market demand, etc.

- Identify the two coffee types with the weakest correlation. Discuss possible reasons for this weak relationship and any external factors that might influence these production types differently.

- Two coffee types with the weakest correlation in production volumes over the years are Arabica/Robusta and Robusta. The correlation coefficient between them is 0.312663, which means that there is a weak relationship between the production volume of these two types of coffee. This indicates that an increase or decrease in the production volume of one type is unlikely to affect the production volume of the other type.